from __future__ import annotations

TEMPERATURE_RANGE_CENTI = (1800, 3600)
HUMIDITY_RANGE_CENTI = (1500, 8500)
ILLUMINANCE_RANGE = (10.0, 3000.0)
PM10_RANGE = (5.0, 120.0)

TEMPERATURE_STD_FRAC = 0.08
HUMIDITY_STD_FRAC = 0.12
ILLUMINANCE_STD_FRAC = 0.15
PM10_STD_FRAC = 0.25

MAX_ROOMS = 6

MIN_DEVICES_PER_ROOM = 4
MAX_DEVICES_PER_ROOM = 10
ALLOW_TYPE_DUPE_MAX = 2

__all__ = [
    "TEMPERATURE_RANGE_CENTI",
    "HUMIDITY_RANGE_CENTI",
    "ILLUMINANCE_RANGE",
    "PM10_RANGE",
    "TEMPERATURE_STD_FRAC",
    "HUMIDITY_STD_FRAC",
    "ILLUMINANCE_STD_FRAC",
    "PM10_STD_FRAC",
    "MAX_ROOMS",
    "MIN_DEVICES_PER_ROOM",
    "MAX_DEVICES_PER_ROOM",
    "ALLOW_TYPE_DUPE_MAX",
]
